artifact_uri: ./mlruns/0/dde95457a2e4445ead563df7a0ee1ae6/artifacts
end_time: 1649939592914
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: dde95457a2e4445ead563df7a0ee1ae6
run_uuid: dde95457a2e4445ead563df7a0ee1ae6
source_name: ''
source_type: 4
source_version: ''
start_time: 1649939590675
status: 3
tags: []
user_id: pierr
